/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JInternalFrame;

/**
 *
 * @author User
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
    }

    void MostrarEnEscritorio(JInternalFrame internal){
       this.jdpnContenedor.removeAll();
       this.jdpnContenedor.repaint();
       this.jdpnContenedor.add(internal);
       internal.setVisible(true);
   } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpnContenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        RegistrosMenu = new javax.swing.JMenu();
        ResumenUsuario = new javax.swing.JMenuItem();
        RegistrarGastos = new javax.swing.JMenu();
        Registrar = new javax.swing.JMenuItem();
        Reporte = new javax.swing.JMenu();
        AbrirReporte = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenu();
        JMCategorias = new javax.swing.JMenuItem();
        JMIngresosGastos = new javax.swing.JMenuItem();
        Notificaciones = new javax.swing.JMenu();
        JMNotificaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jdpnContenedor.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jdpnContenedorLayout = new javax.swing.GroupLayout(jdpnContenedor);
        jdpnContenedor.setLayout(jdpnContenedorLayout);
        jdpnContenedorLayout.setHorizontalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1243, Short.MAX_VALUE)
        );
        jdpnContenedorLayout.setVerticalGroup(
            jdpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );

        RegistrosMenu.setText("Principal");

        ResumenUsuario.setText("Resumen");
        ResumenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumenUsuarioActionPerformed(evt);
            }
        });
        RegistrosMenu.add(ResumenUsuario);

        jMenuBar1.add(RegistrosMenu);

        RegistrarGastos.setText("Registrar Gastos");

        Registrar.setText("Registrar");
        RegistrarGastos.add(Registrar);

        jMenuBar1.add(RegistrarGastos);

        Reporte.setText("Reportes");

        AbrirReporte.setText("Abrir Reporte");
        AbrirReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirReporteActionPerformed(evt);
            }
        });
        Reporte.add(AbrirReporte);

        jMenuBar1.add(Reporte);

        Modificar.setText("Modificar");

        JMCategorias.setText("Categorias");
        Modificar.add(JMCategorias);

        JMIngresosGastos.setText("Ingresos y Gastos");
        Modificar.add(JMIngresosGastos);

        jMenuBar1.add(Modificar);

        Notificaciones.setText("Notificaciones");

        JMNotificaciones.setText("Notificaciones usuario");
        Notificaciones.add(JMNotificaciones);

        jMenuBar1.add(Notificaciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpnContenedor, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResumenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumenUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResumenUsuarioActionPerformed

    private void AbrirReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbrirReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem AbrirReporte;
    public javax.swing.JMenuItem JMCategorias;
    public javax.swing.JMenuItem JMIngresosGastos;
    public javax.swing.JMenuItem JMNotificaciones;
    public javax.swing.JMenu Modificar;
    public javax.swing.JMenu Notificaciones;
    public javax.swing.JMenuItem Registrar;
    public javax.swing.JMenu RegistrarGastos;
    public javax.swing.JMenu RegistrosMenu;
    public javax.swing.JMenu Reporte;
    public javax.swing.JMenuItem ResumenUsuario;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JDesktopPane jdpnContenedor;
    // End of variables declaration//GEN-END:variables
}
